spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=quanlidaotao;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456789
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.web.resources.static-locations=classpath:/static/